# -*- coding: utf-8 -*-
"""Fakenews.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SgGyOniXA4gCl7dKm0hIi8jhlt1dtD0q
"""

import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
import matplotlib.pyplot as plt

"""| Library          | Use                  |
| ---------------- | -------------------- |
| pandas           | Data handling        |
| numpy            | Numerical operations |
| CountVectorizer  | Text → Numbers       |
| train_test_split | Split data           |
| MultinomialNB    | Classification model |
| metrics          | Accuracy calculation |
| matplotlib       | Visualization        |

Load Dataset
"""

df=pd.read_csv('news.csv', index_col=None, on_bad_lines='skip')

"""View Dataset"""

df

"""Remove Unwanted Column

Removes unnecessary index column.

Before:

Unnamed:0
title
text
label

After:

title
text
label
"""

dataset=df.drop("Unnamed: 0",axis=1)

"""View Clean Dataset

Displays cleaned dataset.
"""

dataset

"""Create Target Variable

Stores labels.

Output:

FAKE
REAL
FAKE
REAL
...
"""

y=dataset["label"]

"""Split Data

| Dataset  | Percentage |
| -------- | ---------- |
| Training | 67%        |
| Testing  | 33%        |

"""

X_train, X_test, y_train, y_test = train_test_split(dataset['text'], y, test_size=0.33, random_state=53)

"""Convert Text into Numbers

Machine Learning cannot understand text.


"""

count_vectorizer = CountVectorizer(stop_words='english')
count_train = count_vectorizer.fit_transform(X_train)
print(count_train)
count_test = count_vectorizer.transform(X_test)

"""Check Vocabulary Size"""

dir(count_train)

"""Counts unique words."""

len(count_vectorizer.get_feature_names_out())

"""View Numerical Matrix

Displays text converted to numbers.
"""

print(count_train.toarray())

"""Train Naive Bayes Model

Train model using news articles.

Model learns:

Word patterns
FAKE patterns
REAL patterns

Make Predictions

Predicts labels for unseen news.

Example:

['FAKE','REAL','REAL']
"""

clf = MultinomialNB()

clf.fit(count_train, y_train)
pred = clf.predict(count_test)
score = metrics.accuracy_score(y_test, pred)
print("accuracy:   %0.3f" % score)

cm = metrics.confusion_matrix(y_test, pred, labels=['FAKE', 'REAL'])

"""Classification Report"""

from sklearn.metrics import classification_report

report=classification_report(y_test, pred)

print(report)

"""Display First News Article"""

dataset["text"][0]

"""Display First Vectorized News

Shows numerical representation of first article.
"""

count_train[[0]]

"""Recreate Vectorizer

Rebuild vocabulary.

"""

count_vectorizer = CountVectorizer(stop_words='english')
count_train = count_vectorizer.fit_transform(X_train)
#print(count_train)
#count_test = count_vectorizer.transform(X_test)

"""Check First Training Article"""

#count_input=count_vectorizer.transform([[dataset["text"][0]]])
X_train[[0]]

"""Predict First Article"""

clf.predict(count_train[[0]])

"""| Part        | Meaning                              |
| ----------- | ------------------------------------ |
| array       | Numpy array                          |
| 'FAKE'      | Predicted label                      |
| dtype='<U4' | Unicode string with max 4 characters |

Verify Prediction
"""

print("Actual Label :", y_train.iloc[0])
print("Predicted Label :", clf.predict(count_train[[0]])[0])

"""Confusion Matrix."""

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, pred)

print(cm)

import seaborn as sns
import matplotlib.pyplot as plt

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Fake News Detection Confusion Matrix")
plt.show()

"""Accuracy

Formula:

(TP + TN) / Total

Calculation:

(1003 + 865) / 2091

1868 / 2091

0.8934

======
Accuracy
89.34%

======

Step 4: Error Rate

Formula:

(FP + FN) / Total

Calculation:

143 + 80 = 223

223 / 2091

10.66%

========

| Actual \ Predicted | 0       | 1        |
| ------------------ | ------- | -------- |
| **0**              | **865** | **143**  |
| **1**              | **80**  | **1003** |

========

Assuming:

0 = FAKE

1 = REAL

========

| Metric                      | Value  |
| --------------------------- | ------ |
| Total News Articles         | 2091   |
| Correct Predictions         | 1868   |
| Wrong Predictions           | 223    |
| Accuracy                    | 89.34% |
| Error Rate                  | 10.66% |
| Correct Fake News Detection | 865    |
| Correct Real News Detection | 1003   |

"The first news article was converted into numerical form using CountVectorizer. The Multinomial Naive Bayes model analyzed the word frequencies and predicted the article as FAKE. The output array(['FAKE']) indicates that the model classified the article as fake news based on patterns learned during training."

Classification Report
"""

from sklearn.metrics import classification_report

print(classification_report(y_test, pred))

"""Test Custom News"""

news = ["Scientists discover water on Mars"]

news_vector = count_vectorizer.transform(news)

prediction = clf.predict(news_vector)

print(prediction[0])

news = ["Aliens landed in Chennai yesterday"]
news_vector = count_vectorizer.transform(news)

prediction = clf.predict(news_vector)

print(prediction[0])

news = ["Government announces new education policy for students"]
news_vector = count_vectorizer.transform(news)

prediction = clf.predict(news_vector)

print(prediction[0])

news = ["Government announces new education policy for students"]

news_vector = count_vectorizer.transform(news)

print(clf.predict(news_vector))

print(clf.predict_proba(news_vector))

"""| Class | Probability |
| ----- | ----------- |
| FAKE  | 29%         |
| REAL  | 71%         |

During training:

clf.fit(count_train, y_train)

The model learned which words frequently appear in:

REAL news
FAKE news

Example (simplified):

| Word       | REAL Count | FAKE Count |
| ---------- | ---------- | ---------- |
| government | 500        | 50         |
| policy     | 420        | 30         |
| education  | 350        | 20         |
| students   | 280        | 40         |
| aliens     | 5          | 120        |
| secret     | 15         | 180        |
"""