# -*- coding: utf-8 -*-
"""AppointmentBot AI: Smart Appointment Assistant

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VpC33cLe3lR0MlxqAVnQglPd74Xn5KRl

Import Required Libraries
"""

# ==========================================
# AppointmentBot AI
# Smart Appointment Assistant
# ==========================================

# Data Manipulation
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Text Processing
import re
import string

# Natural Language Processing
import nltk

nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

# Machine Learning
from sklearn.model_selection import train_test_split

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

"""Create Dataset"""

data = {

'Message':[

'I want to book an appointment',
'Can I visit tomorrow?',
'Please schedule my appointment',
'Book a consultation',
'Reserve a slot',
'I need to meet the doctor',
'Can I book for Monday?',
'Schedule my visit',

'Thank you',
'Good Morning',
'Hello',
'Send me the report',
'Where is your clinic?',
'Nice service',
'What are your timings?',
'How much is the consultation fee?'

],

'Label':[

'Booking',
'Booking',
'Booking',
'Booking',
'Booking',
'Booking',
'Booking',
'Booking',

'Non-Booking',
'Non-Booking',
'Non-Booking',
'Non-Booking',
'Non-Booking',
'Non-Booking',
'Non-Booking',
'Non-Booking'

]

}

df = pd.DataFrame(data)

"""Display Dataset"""

df

"""Dataset Information"""

df.shape
df.info()
df.describe()
df.isnull().sum()

"""Class Distribution

Check the number of Booking and Non-Booking messages.
"""

df['Label'].value_counts()

sns.countplot(data=df,x='Label')

plt.title("Booking vs Non-Booking")

plt.show()

"""Text Preprocessing

Clean the text by performing:

Lowercase conversion
Remove punctuation
Remove numbers
Remove stopwords
Apply stemming
"""

stemmer = PorterStemmer()

def preprocess(text):

    text = text.lower()

    text = re.sub(r'[^a-zA-Z]',' ',text)

    words = text.split()

    words = [stemmer.stem(word)
             for word in words
             if word not in stopwords.words('english')]

    return " ".join(words)

"""Apply preprocessing"""

df['Clean_Text'] = df['Message'].apply(preprocess)

df

"""Feature and Target

Separate the independent and dependent variables.
"""

X = df['Clean_Text']

y = df['Label']

"""Train-Test Split

Split the dataset into training and testing sets.
"""

X_train,X_test,y_train,y_test=train_test_split(

X,
y,
test_size=0.20,
random_state=42

)

"""CountVectorizer

Convert text into numerical features using CountVectorizer.
"""

cv=CountVectorizer()

X_train_cv=cv.fit_transform(X_train)

X_test_cv=cv.transform(X_test)

"""Model 1

CountVectorizer + Naive Bayes

Train a Multinomial Naive Bayes model.
"""

nb=MultinomialNB()

nb.fit(X_train_cv,y_train)

pred_nb=nb.predict(X_test_cv)

print("Accuracy :",accuracy_score(y_test,pred_nb))

"""Classification Report"""

print(classification_report(y_test,pred_nb))

"""Confusion Matrix"""

sns.heatmap(confusion_matrix(y_test,pred_nb),
annot=True,
fmt='d',
cmap='Blues')

plt.show()

"""CountVectorizer + Logistic Regression"""

lr=LogisticRegression(max_iter=1000)

lr.fit(X_train_cv,y_train)

pred_lr=lr.predict(X_test_cv)

print("Accuracy :",accuracy_score(y_test,pred_lr))

"""CountVectorizer + Linear SVM"""

svm=LinearSVC()

svm.fit(X_train_cv,y_train)

pred_svm=svm.predict(X_test_cv)

print("Accuracy :",accuracy_score(y_test,pred_svm))

"""TF-IDF Vectorizer

Convert text into TF-IDF vectors.
"""

tfidf=TfidfVectorizer()

X_train_tf=tfidf.fit_transform(X_train)

X_test_tf=tfidf.transform(X_test)

"""TF-IDF + Naive Bayes"""

model=MultinomialNB()

model.fit(X_train_tf,y_train)

pred=model.predict(X_test_tf)

print("Accuracy :",accuracy_score(y_test,pred))

"""TF-IDF + Logistic Regression"""

model=LogisticRegression(max_iter=1000)

model.fit(X_train_tf,y_train)

pred=model.predict(X_test_tf)

print("Accuracy :",accuracy_score(y_test,pred))

"""TF-IDF + Linear SVM"""

model=LinearSVC()

model.fit(X_train_tf,y_train)

pred=model.predict(X_test_tf)

print("Accuracy :",accuracy_score(y_test,pred))

"""Compare Models


Compare the accuracy of all models to identify the best-performing one.
"""

results=pd.DataFrame({

'Model':[

'CV + Naive Bayes',
'CV + Logistic Regression',
'CV + Linear SVM',

'TFIDF + Naive Bayes',
'TFIDF + Logistic Regression',
'TFIDF + Linear SVM'

],

'Accuracy':[

accuracy_score(y_test,pred_nb),
accuracy_score(y_test,pred_lr),
accuracy_score(y_test,pred_svm),

accuracy_score(y_test,MultinomialNB().fit(X_train_tf,y_train).predict(X_test_tf)),
accuracy_score(y_test,LogisticRegression(max_iter=1000).fit(X_train_tf,y_train).predict(X_test_tf)),
accuracy_score(y_test,LinearSVC().fit(X_train_tf,y_train).predict(X_test_tf))

]

})

results

"""Best Model

Sort the models based on accuracy.
"""

results.sort_values(by='Accuracy',ascending=False)

"""Predict New Message

Test the trained model with unseen customer messages.
"""

message=["Can I book an appointment tomorrow?"]

message=[preprocess(i) for i in message]

message=tfidf.transform(message)

prediction=model.predict(message)

print(prediction[0])

"""Another Example"""

message=["Thank you for your service"]

message=[preprocess(i) for i in message]

message=tfidf.transform(message)

prediction=model.predict(message)

print(prediction[0])