# -*- coding: utf-8 -*-
"""Movie_Review_Sentiment_Analysis_Using_TF_IDF_Vectorizer_and_Multinomial_Naive_Bayes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PHQ8XSUmnK3LIqJ1kzoM-veECwWL3uj8

Import Libraries
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

import seaborn as sns
import matplotlib.pyplot as plt

import pandas as pd

df = pd.read_csv("IMDB Dataset.csv", engine='python', on_bad_lines='warn')

df.head()

"""Check Dataset Shape"""

print("Rows and Columns:")
print(df.shape)

"""| Item    | Value |
| ------- | ----- |
| Reviews | 16602 |
| Columns | 2     |

Check Columns
"""

print(df.columns)

"""Check Class Distribution"""

df['sentiment'].value_counts()

"""Check Missing Values"""

df.isnull().sum()

"""Show One Positive Review"""

positive = df[df['sentiment']=='positive']

print(positive.iloc[0]['review'])

"""Show One Negative Review"""

negative = df[df['sentiment']=='negative']

print(negative.iloc[0]['review'])

"""| Parameter        | Value                      |
| ---------------- | -------------------------- |
| Dataset Name     | IMDb Movie Reviews Dataset |
| Total Reviews    | 50,000                     |
| Positive Reviews | 25,000                     |
| Negative Reviews | 25,000                     |
| Features         | Review Text                |
| Target           | Sentiment                  |
| NLP Task         | Sentiment Analysis         |
| Vectorizer       | TF-IDF                     |
| Algorithm        | Multinomial Naive Bayes    |

"""

df.head()
df.shape
df.columns
df['sentiment'].value_counts()

"""Train-Test Split"""

from sklearn.model_selection import train_test_split

X = df['review']
y = df['sentiment']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Data:", X_train.shape)
print("Testing Data:", X_test.shape)

"""| Code                                                   | Description                                                   |
| ------------------------------------------------------ | ------------------------------------------------------------- |
| `from sklearn.model_selection import train_test_split` | Imports the train_test_split function from Scikit-Learn.      |
| `X = df['review']`                                     | Stores movie review text as input features.                   |
| `y = df['sentiment']`                                  | Stores sentiment labels (positive/negative) as target values. |
| `train_test_split()`                                   | Splits dataset into training and testing datasets.            |
| `test_size=0.2`                                        | Uses 20% data for testing and 80% for training.               |
| `random_state=42`                                      | Ensures the same split every time the code runs.              |
| `X_train`                                              | Training review texts.                                        |
| `X_test`                                               | Testing review texts.                                         |
| `y_train`                                              | Training sentiment labels.                                    |
| `y_test`                                               | Testing sentiment labels.                                     |
| `X_train.shape`                                        | Displays number of training records.                          |
| `X_test.shape`                                         | Displays number of testing records.                           |

=========
| Variable  | Meaning                       |
| --------- | ----------------------------- |
| `X`       | Review text column            |
| `y`       | Sentiment column              |
| `X_train` | Reviews used for training     |
| `X_test`  | Reviews used for testing      |
| `y_train` | Sentiment labels for training |
| `y_test`  | Sentiment labels for testing  |

==========
Workflow
--------


| Step | Input                       | Output                  |
| ---- | --------------------------- | ----------------------- |
| 1    | IMDb Dataset                | 16,602 Reviews          |
| 2    | Train-Test Split (80:20)    | Training & Testing Data |
| 3    | Training Data (13,281)      | Model Learns Patterns   |
| 4    | Testing Data (3,321)        | Model Predictions       |
| 5    | Compare Actual vs Predicted | Accuracy Score          |

TF-IDF Vectorization
"""

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    stop_words='english'
)

X_train_tfidf = tfidf.fit_transform(X_train)

X_test_tfidf = tfidf.transform(X_test)

print(X_train_tfidf.shape)
print(X_test_tfidf.shape)

"""Training Data

(13281, 59122)

| Item    |  Value | Meaning                 |
| ------- | -----: | ----------------------- |
| Rows    | 13,281 | Training movie reviews  |
| Columns | 59,122 | Unique words (features) |

--------------

Testing Data
(3321, 59122)

| Value  | Meaning                                      |
| ------ | -------------------------------------------- |
| 59,122 | Total unique words found in training reviews |

Examples:

movie
excellent
worst
fantastic
boring
acting
story

Each word becomes one column (feature).

-------------

"TF-IDF converts text reviews into numerical values. Unlike CountVectorizer, TF-IDF gives higher importance to meaningful words and lower importance to frequently occurring common words."

============

| Code                                                          | Description                                                                             |
| ------------------------------------------------------------- | --------------------------------------------------------------------------------------- |
| `from sklearn.feature_extraction.text import TfidfVectorizer` | Imports the TF-IDF Vectorizer.                                                          |
| `tfidf = TfidfVectorizer(stop_words='english')`               | Creates a TF-IDF object and removes common English words like "is", "the", "and".       |
| `tfidf.fit_transform(X_train)`                                | Learns vocabulary from training reviews and converts text into TF-IDF numerical values. |
| `X_train_tfidf`                                               | Stores TF-IDF vectors of training reviews.                                              |
| `tfidf.transform(X_test)`                                     | Converts test reviews using the same vocabulary learned from training data.             |
| `X_test_tfidf`                                                | Stores TF-IDF vectors of testing reviews.                                               |
| `X_train_tfidf.shape`                                         | Displays rows and columns of training TF-IDF matrix.                                    |
| `X_test_tfidf.shape`                                          | Displays rows and columns of testing TF-IDF matrix.                                     |

=======

Model Training
"""

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(
    X_train_tfidf,
    y_train
)

"""Prediction & Accuracy"""

from sklearn.metrics import accuracy_score

pred = model.predict(X_test_tfidf)

accuracy = accuracy_score(
    y_test,
    pred
)

print("Accuracy:", round(accuracy*100,2), "%")

"""| Metric           | Value                   |
| ---------------- | ----------------------- |
| Algorithm        | Multinomial Naive Bayes |
| Vectorizer       | TF-IDF                  |
| Accuracy         | **85.31%**              |
| Training Reviews | 13,281                  |
| Testing Reviews  | 3,321                   |

Confusion Matrix
"""

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, pred)

print(cm)

plt.figure(figsize=(6,4))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.title("Movie Review Sentiment Analysis")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

"""Since the diagonal values (1512 and 1321) are much larger than the error values (138 and 350), the model is performing well.

| Actual \ Predicted | Negative (0) | Positive (1) |
| ------------------ | -----------: | -----------: |
| **Negative (0)**   |     **1512** |      **138** |
| **Positive (1)**   |      **350** |     **1321** |

=====

| Metric              | Value | Meaning                                            |
| ------------------- | ----: | -------------------------------------------------- |
| True Negative (TN)  |  1512 | Negative reviews correctly predicted as Negative   |
| False Positive (FP) |   138 | Negative reviews incorrectly predicted as Positive |
| False Negative (FN) |   350 | Positive reviews incorrectly predicted as Negative |
| True Positive (TP)  |  1321 | Positive reviews correctly predicted as Positive   |

====
| Category                     | Count |
| ---------------------------- | ----: |
| Correct Negative Predictions |  1512 |
| Correct Positive Predictions |  1321 |
| Total Correct Predictions    |  2833 |
| Total Wrong Predictions      |   488 |
| Total Test Reviews           |  3321 |
=====
Accuracy Calculation

| Formula                      | Value                |
| ---------------------------- | -------------------- |
| Accuracy = (TP + TN) / Total | (1321 + 1512) / 3321 |
| Accuracy                     | 2833 / 3321          |
| Accuracy %                   | **85.31%**           |

=========

Error Analysis

| Error Type     | Count | Meaning                               |
| -------------- | ----: | ------------------------------------- |
| False Positive |   138 | Negative review predicted as Positive |
| False Negative |   350 | Positive review predicted as Negative |
| Total Errors   |   488 | Incorrect predictions                 |

========
Model Performance Table

| Observation                           | Result |
| ------------------------------------- | ------ |
| Correctly Classified Negative Reviews | 1512   |
| Correctly Classified Positive Reviews | 1321   |
| Total Correct Predictions             | 2833   |
| Total Incorrect Predictions           | 488    |
| Accuracy                              | 85.31% |
| Model Performance                     | Good   |

Classification Report
"""

from sklearn.metrics import classification_report

report = classification_report(
    y_test,
    pred
)

print(report)

"""| Observation       | Result                 |
| ----------------- | ---------------------- |
| Best Precision    | Positive Reviews (91%) |
| Best Recall       | Negative Reviews (92%) |
| Best F1-Score     | Negative Reviews (86%) |
| Overall Accuracy  | 85%                    |
| Model Performance | Good                   |
| Dataset Balance   | Balanced               |

Final Conclusion Table
---------------------

| Parameter                 | Result                                                      |
| ------------------------- | ----------------------------------------------------------- |
| Project                   | Movie Review Sentiment Analysis                             |
| Vectorizer                | TF-IDF                                                      |
| Algorithm                 | Multinomial Naive Bayes                                     |
| Accuracy                  | 85.31%                                                      |
| Negative Review Recall    | 92%                                                         |
| Positive Review Precision | 91%                                                         |
| F1-Score Range            | 84%–86%                                                     |
| Result                    | Successfully classified Positive and Negative movie reviews |

Test Custom Movie Review
"""

review = ["This movie was fantastic and amazing"]

review_vector = tfidf.transform(review)

prediction = model.predict(review_vector)

print("Sentiment:", prediction[0])

"""| Step | Code                                                | Result                           |
| ---- | --------------------------------------------------- | -------------------------------- |
| 1    | `review = ["This movie was fantastic and amazing"]` | User enters review text          |
| 2    | `tfidf.transform(review)`                           | Converts text into TF-IDF values |
| 3    | `review_vector`                                     | Numerical representation         |
| 4    | `model.predict(review_vector)`                      | Predicts positive or negative    |

============

TF-IDF Vocabulary

| Word      | TF-IDF Weight |
| --------- | ------------: |
| movie     |          0.12 |
| fantastic |          0.78 |
| amazing   |          0.81 |

Converted to:

[0.12, 0.78, 0.81]

This is called Vectorization.
==========

Negative Review
"""

review = ["Worst movie I have ever watched"]

review_vector = tfidf.transform(review)

prediction = model.predict(review_vector)

print("Sentiment:", prediction[0])

"""During Training
---------------

X_train_tfidf = tfidf.fit_transform(X_train)

| Method          | Purpose                 |
| --------------- | ----------------------- |
| fit()           | Learn vocabulary        |
| transform()     | Convert text to numbers |
| fit_transform() | Do both together        |

===========

During Prediction
review_vector = tfidf.transform(review)

We use only:

transform()

because the vocabulary is already learned from training data.

===========

Interactive Prediction
"""

review = [input("Enter Movie Review: ")]

review_vector = tfidf.transform(review)

prediction = model.predict(review_vector)

print("Predicted Sentiment:", prediction[0])

"""Show Probability"""

review = ["This movie was fantastic"]

review_vector = tfidf.transform(review)

print(model.predict(review_vector))

print(model.predict_proba(review_vector))

"""| Class    | Probability |
| -------- | ----------- |
| Negative | 19%         |
| Positive | 81%         |

Final Conclusion
"""

print("""
Project Completed Successfully

Project:
Movie Review Sentiment Analysis

Vectorizer:
TF-IDF

Algorithm:
Multinomial Naive Bayes

Accuracy:
85.31%

Result:
Successfully classified Positive and Negative Movie Reviews.
""")