# -*- coding: utf-8 -*-
"""AppointmentBot_AI_Intelligent_Appointment_Booking_Assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XbCJZqd38oqFWWh9RMsVhTBm5mmVFYoD

Import Required Libraries
"""

# ==========================================================
# AppointmentBot AI : Smart Appointment Assistant
# Part 1 : Import Libraries
# ==========================================================

# Data Manipulation
import pandas as pd
import numpy as np

# Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

# NLP Libraries
import re
import string
import nltk

# Download NLTK Resources
nltk.download('stopwords')
nltk.download('punkt')

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

# Machine Learning
from sklearn.model_selection import train_test_split

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

print("All libraries imported successfully.")

"""Load Dataset"""

# Load Dataset

df = pd.read_csv("appointment_booking_dataset.csv")

df.head()

"""Display Dataset Shape"""

print("Dataset Shape :", df.shape)

"""Display Column Names"""

print(df.columns)

"""Dataset Information"""

df.info()

"""Check Missing Values"""

df.isnull().sum()

"""Check Duplicate Records"""

print("Duplicate Records :", df.duplicated().sum())

df = df.drop_duplicates()

print("Shape After Removing Duplicates :", df.shape)

"""Display Random Records

Display random messages to better understand the dataset.
"""

df.sample(10)

"""Class Distribution

Check the number of Booking and Non-Booking messages
"""

df['Label'].value_counts()

"""Count Plot

Visualize Booking and Non-Booking messages.
"""

plt.figure(figsize=(6,5))

sns.countplot(
    data=df,
    x='Label',
    palette='Set2'
)

plt.title("Booking vs Non-Booking Messages")

plt.xlabel("Message Category")

plt.ylabel("Count")

plt.show()

"""Pie Chart"""

plt.figure(figsize=(6,6))

df['Label'].value_counts().plot(

    kind='pie',

    autopct='%1.1f%%',

    colors=['skyblue','lightgreen'],

    startangle=90

)

plt.ylabel("")

plt.title("Booking vs Non-Booking Distribution")

plt.show()

"""Message Length"""

df['Message_Length'] = df['Message'].apply(len)

df[['Message','Message_Length']].head()

"""Message Length Statistics"""

df['Message_Length'].describe()

"""Histogram"""

plt.figure(figsize=(8,5))

plt.hist(

    df['Message_Length'],

    bins=30,

    color='orange',

    edgecolor='black'

)

plt.title("Distribution of Message Length")

plt.xlabel("Characters")

plt.ylabel("Frequency")

plt.show()

"""Booking vs Non-Booking Message Length"""

plt.figure(figsize=(8,5))

sns.boxplot(

    data=df,

    x='Label',

    y='Message_Length',

    palette='Set3'

)

plt.title("Message Length Comparison")

plt.show()

"""Summary"""

print("="*60)

print("Dataset Summary")

print("="*60)

print("Total Records :", len(df))

print("Total Columns :", len(df.columns))

print()

print(df['Label'].value_counts())

print("="*60)

"""**Text Preprocessing and NLP**"""

# Install WordCloud (Run only once)
!pip install wordcloud

from wordcloud import WordCloud

"""Display Original Messages"""

df[['Message']].head(10)

"""Create Stopwords and Stemmer"""

stop_words = set(stopwords.words('english'))

stemmer = PorterStemmer()

"""Create Preprocessing Function"""

def preprocess(text):

    # Convert to lowercase
    text = text.lower()

    # Remove numbers and punctuation
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    # Tokenization
    words = text.split()

    # Remove stopwords
    words = [word for word in words if word not in stop_words]

    # Stemming
    words = [stemmer.stem(word) for word in words]

    # Join words
    return " ".join(words)

"""Apply Preprocessing"""

df['Clean_Text'] = df['Message'].apply(preprocess)

df[['Message','Clean_Text']].head(10)

"""Check Missing Values"""

df['Clean_Text'].isnull().sum()

"""Calculate Word Count

Find the number of words in each cleaned message.
"""

df['Word_Count'] = df['Clean_Text'].apply(lambda x: len(x.split()))

df[['Clean_Text','Word_Count']].head()

"""Word Count Statistics

Display descriptive statistics for the cleaned text.
"""

df['Word_Count'].describe()

"""Histogram of Word Count

Visualize the distribution of words per message.
"""

plt.figure(figsize=(8,5))

plt.hist(
    df['Word_Count'],
    bins=20,
    edgecolor='black'
)

plt.title("Word Count Distribution")

plt.xlabel("Number of Words")

plt.ylabel("Frequency")

plt.show()

"""Booking Word Cloud

Generate a Word Cloud for Booking messages
"""

booking_text = " ".join(

    df[df['Label']=="Booking"]['Clean_Text']

)

wordcloud = WordCloud(

    width=900,
    height=500,
    background_color='white'

).generate(booking_text)

plt.figure(figsize=(12,6))

plt.imshow(wordcloud)

plt.axis("off")

plt.title("Booking Messages Word Cloud")

plt.show()

"""Non-Booking Word Cloud

Generate a Word Cloud for Non-Booking messages.
"""

non_booking_text = " ".join(

    df[df['Label']=="Non-Booking"]['Clean_Text']

)

wordcloud = WordCloud(

    width=900,
    height=500,
    background_color='white'

).generate(non_booking_text)

plt.figure(figsize=(12,6))

plt.imshow(wordcloud)

plt.axis("off")

plt.title("Non-Booking Messages Word Cloud")

plt.show()

"""Most Frequent Words


Count the frequency of words in all messages.
"""

from collections import Counter

all_words = " ".join(df['Clean_Text']).split()

word_frequency = Counter(all_words)

word_frequency.most_common(20)

"""Top 20 Frequent Words

Display the most common words.
"""

top_words = pd.DataFrame(

    word_frequency.most_common(20),

    columns=['Word','Frequency']

)

top_words

"""Visualize Top Words

Plot the 20 most frequent words.
"""

plt.figure(figsize=(12,6))

plt.bar(

    top_words['Word'],

    top_words['Frequency']

)

plt.xticks(rotation=45)

plt.title("Top 20 Frequent Words")

plt.xlabel("Words")

plt.ylabel("Frequency")

plt.show()

"""Booking Messages Only

Display a few Booking messages after preprocessing.
"""

df[df['Label']=="Booking"][
    ['Message','Clean_Text']
].head(10)

"""Non-Booking Messages Only

Display a few Non-Booking messages after preprocessing.
"""

df[df['Label']=="Non-Booking"][
    ['Message','Clean_Text']
].head(10)

"""Save Preprocessed Dataset

Save the cleaned dataset for future use.
"""

df.to_csv(

    "appointment_booking_cleaned_dataset.csv",

    index=False

)

print("Preprocessed dataset saved successfully.")

"""Display Final Dataset

Display the first few rows of the final dataset.
"""

df.head()

"""Summary

Print a summary after preprocessing.
"""

print("="*60)

print("Text Preprocessing Completed Successfully")

print("="*60)

print("Total Records :",len(df))

print("Total Features :",len(df.columns))

print()

print(df.head())

print("="*60)

"""**Feature Extraction and Model Training**

Feature and Target Selection

Separate the independent feature (Clean_Text) and target variable (Label)
"""

# ============================================
# Feature and Target
# ============================================

X = df['Clean_Text']

y = df['Label']

print("Feature Shape :", X.shape)
print("Target Shape :", y.shape)

"""Train-Test Split"""

# ============================================
# Train-Test Split
# ============================================

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y

)

print("Training Samples :", len(X_train))
print("Testing Samples :", len(X_test))

"""Feature Extraction Using CountVectorizer"""

# ============================================
# CountVectorizer
# ============================================

cv = CountVectorizer()

"""Fit training data"""

X_train_cv = cv.fit_transform(X_train)

"""Transform testing data"""

X_test_cv = cv.transform(X_test)

"""Display Shape"""

print("Training Matrix Shape :", X_train_cv.shape)

print("Testing Matrix Shape :", X_test_cv.shape)

"""Display Vocabulary Size


Display total number of unique words learned.
"""

print("Vocabulary Size :", len(cv.vocabulary_))

"""Display Sample Vocabulary


Display first 20 words.
"""

list(cv.vocabulary_.keys())[:20]

"""MODEL 1
CountVectorizer + Multinomial Naive Bayes

Train Naive Bayes Model


Multinomial Naive Bayes is one of the most popular algorithms for text classification.
"""

# ============================================
# Multinomial Naive Bayes
# ============================================

nb_model = MultinomialNB()

nb_model.fit(X_train_cv, y_train)

"""Prediction"""

nb_prediction = nb_model.predict(X_test_cv)

"""Accuracy"""

nb_accuracy = accuracy_score(y_test, nb_prediction)

print("Naive Bayes Accuracy :", nb_accuracy)

"""Classification Report"""

print(classification_report(y_test, nb_prediction))

"""Confusion Matrix"""

cm = confusion_matrix(y_test, nb_prediction)

plt.figure(figsize=(5,4))

sns.heatmap(

    cm,

    annot=True,

    fmt='d',

    cmap='Blues',

    xticklabels=['Booking','Non-Booking'],

    yticklabels=['Booking','Non-Booking']

)

plt.title("Naive Bayes Confusion Matrix")

plt.xlabel("Predicted")

plt.ylabel("Actual")

plt.show()

"""MODEL 2
CountVectorizer + Logistic Regression

Train Logistic Regression


Logistic Regression performs well for binary text classification problems.
"""

lr_model = LogisticRegression(

    max_iter=1000

)

lr_model.fit(

    X_train_cv,

    y_train

)

"""Prediction"""

lr_prediction = lr_model.predict(X_test_cv)

"""Accuracy"""

lr_accuracy = accuracy_score(

    y_test,

    lr_prediction

)

print("Logistic Regression Accuracy :", lr_accuracy)

"""Classification Report"""

print(classification_report(

    y_test,

    lr_prediction

))

"""Confusion Matrix"""

cm = confusion_matrix(

    y_test,

    lr_prediction

)

plt.figure(figsize=(5,4))

sns.heatmap(

    cm,

    annot=True,

    fmt='d',

    cmap='Greens',

    xticklabels=['Booking','Non-Booking'],

    yticklabels=['Booking','Non-Booking']

)

plt.title("Logistic Regression Confusion Matrix")

plt.show()

"""MODEL 3
CountVectorizer + Linear SVM

Train Linear SVM

Linear SVM is one of the highest-performing algorithms for NLP classification.
"""

svm_model = LinearSVC()

svm_model.fit(

    X_train_cv,

    y_train

)

"""Prediction"""

svm_prediction = svm_model.predict(

    X_test_cv

)

"""Accuracy"""

svm_accuracy = accuracy_score(

    y_test,

    svm_prediction

)

print("Linear SVM Accuracy :", svm_accuracy)

"""Classification Report"""

print(classification_report(

    y_test,

    svm_prediction

))

"""Confusion Matrix"""

cm = confusion_matrix(

    y_test,

    svm_prediction

)

plt.figure(figsize=(5,4))

sns.heatmap(

    cm,

    annot=True,

    fmt='d',

    cmap='Oranges',

    xticklabels=['Booking','Non-Booking'],

    yticklabels=['Booking','Non-Booking']

)

plt.title("Linear SVM Confusion Matrix")

plt.show()

"""Compare Model Accuracy

Compare the performance of all three CountVectorizer models.
"""

comparison = pd.DataFrame({

    "Model":[

        "CountVectorizer + Naive Bayes",

        "CountVectorizer + Logistic Regression",

        "CountVectorizer + Linear SVM"

    ],

    "Accuracy":[

        nb_accuracy,

        lr_accuracy,

        svm_accuracy

    ]

})

comparison

"""Accuracy Bar Chart

Visualize model accuracy.
"""

plt.figure(figsize=(8,5))

plt.bar(

    comparison['Model'],

    comparison['Accuracy']

)

plt.xticks(rotation=15)

plt.ylabel("Accuracy")

plt.title("CountVectorizer Model Comparison")

plt.show()

"""Best Model

Identify the best-performing CountVectorizer model.
"""

best_model = comparison.sort_values(

    by="Accuracy",

    ascending=False

)

best_model

"""Test the Best Model


Predict the intent of a new customer message.
"""

new_message = [

    "Can I schedule an appointment for tomorrow?"

]

"""Preprocess"""

clean = [preprocess(text) for text in new_message]

"""Vectorize"""

vector = cv.transform(clean)

"""Prediction"""

prediction = svm_model.predict(vector)

print("Prediction :", prediction[0])

"""Another Test"""

new_message = [

    "Thank you for your support"

]

clean = [preprocess(text) for text in new_message]

vector = cv.transform(clean)

prediction = svm_model.predict(vector)

print("Prediction :", prediction[0])

"""Feature Extraction Using TF-IDF

Convert the cleaned text into TF-IDF vectors.
"""

# ==========================================================
# Feature Extraction Using TF-IDF
# ==========================================================

tfidf = TfidfVectorizer()

"""Fit the training data."""

X_train_tfidf = tfidf.fit_transform(X_train)

"""Transform the testing data."""

X_test_tfidf = tfidf.transform(X_test)

"""Display matrix size."""

print("Training Matrix Shape :", X_train_tfidf.shape)

print("Testing Matrix Shape :", X_test_tfidf.shape)

"""Display Vocabulary Size


Display the total number of unique words learned by the TF-IDF vectorizer.
"""

print("Vocabulary Size :", len(tfidf.vocabulary_))

"""Display Sample Vocabulary"""

list(tfidf.vocabulary_.keys())[:20]

"""Model 1

TF-IDF + Multinomial Naive Bayes
"""

Train the Model


Train the Multinomial Naive Bayes model using TF-IDF features.

tfidf_nb = MultinomialNB()

tfidf_nb.fit(

    X_train_tfidf,

    y_train

)

"""Prediction"""

tfidf_nb_prediction = tfidf_nb.predict(

    X_test_tfidf

)

"""Accuracy"""

tfidf_nb_accuracy = accuracy_score(

    y_test,

    tfidf_nb_prediction

)

print("TF-IDF + Naive Bayes Accuracy :", tfidf_nb_accuracy)

"""Classification Report"""

print(classification_report(

    y_test,

    tfidf_nb_prediction

))

"""

Confusion Matrix
"""

cm = confusion_matrix(

    y_test,

    tfidf_nb_prediction

)

plt.figure(figsize=(5,4))

sns.heatmap(

    cm,

    annot=True,

    fmt='d',

    cmap='Blues',

    xticklabels=['Booking','Non-Booking'],

    yticklabels=['Booking','Non-Booking']

)

plt.title("TF-IDF + Naive Bayes")

plt.xlabel("Predicted")

plt.ylabel("Actual")

plt.show()

"""Model 2

TF-IDF + Logistic Regression

Train the Model
"""

tfidf_lr = LogisticRegression(

    max_iter=1000

)

tfidf_lr.fit(

    X_train_tfidf,

    y_train

)

"""Prediction"""

tfidf_lr_prediction = tfidf_lr.predict(

    X_test_tfidf

)

"""Accuracy"""

tfidf_lr_accuracy = accuracy_score(

    y_test,

    tfidf_lr_prediction

)

print("TF-IDF + Logistic Regression Accuracy :", tfidf_lr_accuracy)

"""Classification Report"""

print(classification_report(

    y_test,

    tfidf_lr_prediction

))

"""Confusion Matrix"""

cm = confusion_matrix(

    y_test,

    tfidf_lr_prediction

)

plt.figure(figsize=(5,4))

sns.heatmap(

    cm,

    annot=True,

    fmt='d',

    cmap='Greens',

    xticklabels=['Booking','Non-Booking'],

    yticklabels=['Booking','Non-Booking']

)

plt.title("TF-IDF + Logistic Regression")

plt.show()

"""Model 3
TF-IDF + Linear SVM

Train the Model
"""

tfidf_svm = LinearSVC()

tfidf_svm.fit(

    X_train_tfidf,

    y_train

)

"""Prediction"""

tfidf_svm_prediction = tfidf_svm.predict(

    X_test_tfidf

)

"""Accuracy"""

tfidf_svm_accuracy = accuracy_score(

    y_test,

    tfidf_svm_prediction

)

print("TF-IDF + Linear SVM Accuracy :", tfidf_svm_accuracy)

"""Classification Report"""

print(classification_report(

    y_test,

    tfidf_svm_prediction

))

"""Confusion Matrix"""

cm = confusion_matrix(

    y_test,

    tfidf_svm_prediction

)

plt.figure(figsize=(5,4))

sns.heatmap(

    cm,

    annot=True,

    fmt='d',

    cmap='Oranges',

    xticklabels=['Booking','Non-Booking'],

    yticklabels=['Booking','Non-Booking']

)

plt.title("TF-IDF + Linear SVM")

plt.xlabel("Predicted")

plt.ylabel("Actual")

plt.show()

"""Compare TF-IDF Models

Compare the accuracy of all three TF-IDF models.
"""

tfidf_results = pd.DataFrame({

    "Model":[

        "TF-IDF + Naive Bayes",

        "TF-IDF + Logistic Regression",

        "TF-IDF + Linear SVM"

    ],

    "Accuracy":[

        tfidf_nb_accuracy,

        tfidf_lr_accuracy,

        tfidf_svm_accuracy

    ]

})

tfidf_results

"""Accuracy Comparison Chart

Visualize the model accuracies.
"""

plt.figure(figsize=(8,5))

plt.bar(

    tfidf_results['Model'],

    tfidf_results['Accuracy']

)

plt.xticks(rotation=15)

plt.ylabel("Accuracy")

plt.title("TF-IDF Model Comparison")

plt.show()

"""Best TF-IDF Model"""

tfidf_results.sort_values(

    by="Accuracy",

    ascending=False

)

"""Test the Best Model


Predict the intent of a new customer message.
"""

message = [

    "Can I book an appointment for tomorrow?"

]

clean_message = [preprocess(text) for text in message]

vector = tfidf.transform(clean_message)

prediction = tfidf_svm.predict(vector)

print("Prediction :", prediction[0])

"""Another Test"""

message = [

    "Thank you for your support."

]

clean_message = [preprocess(text) for text in message]

vector = tfidf.transform(clean_message)

prediction = tfidf_svm.predict(vector)

print("Prediction :", prediction[0])

"""**Model Comparison, Save Model & Build AppointmentBot AI**

Import Joblib

Joblib is used to save and load trained machine learning models.
"""

# ==========================================================
# Import Joblib
# ==========================================================

import joblib

"""Compare All Models


Create a comparison table containing the accuracy of all six models.
"""

# ==========================================================
# Model Comparison
# ==========================================================

comparison = pd.DataFrame({

    "Model":[

        "CountVectorizer + Naive Bayes",

        "CountVectorizer + Logistic Regression",

        "CountVectorizer + Linear SVM",

        "TF-IDF + Naive Bayes",

        "TF-IDF + Logistic Regression",

        "TF-IDF + Linear SVM"

    ],

    "Accuracy":[

        nb_accuracy,

        lr_accuracy,

        svm_accuracy,

        tfidf_nb_accuracy,

        tfidf_lr_accuracy,

        tfidf_svm_accuracy

    ]

})

comparison

"""Accuracy Comparison Chart


Visualize the accuracy of all six models.
"""

plt.figure(figsize=(12,6))

plt.bar(

    comparison["Model"],

    comparison["Accuracy"]

)

plt.xticks(rotation=20)

plt.ylabel("Accuracy")

plt.title("Machine Learning Model Comparison")

plt.show()

"""Sort Models


Arrange models from highest to lowest accuracy.
"""

comparison.sort_values(

    by="Accuracy",

    ascending=False

)

"""Select Best Model"""

# ==========================================================
# Select Best Model
# ==========================================================

best_model = svm_model

best_vectorizer = cv

print("Best Model : CountVectorizer + Linear SVM")

"""Save Model"""

import joblib

joblib.dump(best_model, "appointment_bot_model.pkl")
joblib.dump(best_vectorizer, "count_vectorizer.pkl")

print("Model and Vectorizer Saved Successfully!")

"""Load Model"""

loaded_model = joblib.load("appointment_bot_model.pkl")
loaded_vectorizer = joblib.load("count_vectorizer.pkl")

"""Prediction Function"""

def predict_booking(message):

    clean = preprocess(message)

    vector = loaded_vectorizer.transform([clean])

    prediction = loaded_model.predict(vector)

    return prediction[0]

"""Test Message 1


Predict a booking request.
"""

message = "Can I schedule an appointment for tomorrow?"

print("Message :", message)

print("Prediction :", predict_booking(message))

"""Test Message 2"""

message = "Please reserve a slot for Monday."

print("Prediction :", predict_booking(message))

"""Test Message 3"""

message = "Thank you very much."

print("Prediction :", predict_booking(message))

"""Test Message 4"""

message = "Good Morning"

print("Prediction :", predict_booking(message))

"""Build AppointmentBot AI


Create a chatbot that continuously accepts user input until the user types exit.
"""

# ==========================================================
# AppointmentBot AI
# ==========================================================

print("="*60)

print(" AppointmentBot AI : Smart Appointment Assistant ")

print("="*60)

print("Type 'exit' to stop the chatbot.")

print("="*60)

while True:

    user_message = input("\nYou : ")

    if user_message.lower() == "exit":

        print("\nAppointmentBot AI : Thank you. Goodbye!")

        break

    prediction = predict_booking(user_message)

    print("\nAppointmentBot AI :", prediction)

"""Batch Prediction


Predict multiple customer messages at once.
"""

messages = [

    "Book an appointment for tomorrow",

    "Good Morning",

    "Reserve my appointment",

    "Where is your clinic?",

    "Can I visit on Friday?",

    "Thank you"

]

for msg in messages:

    print("-"*60)

    print("Message :", msg)

    print("Prediction :", predict_booking(msg))

"""Verify Saved Files


Check whether the model files have been saved successfully.
"""

import os

print(os.listdir())

"""Project Summary"""

print("="*60)

print("AppointmentBot AI Project Summary")

print("="*60)

print("Project Name : AppointmentBot AI")

print("Dataset Size :", len(df))

print("Number of Features :", len(df.columns))

print("Best Model : TF-IDF + Linear SVM")

print("Task : Appointment Booking Intent Detection")

print("="*60)