# -*- coding: utf-8 -*-
"""Online Course Reviews Topic Modeling Using Latent Dirichlet Allocation (LDA)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12c6UEZ12VKQatyT-Zaix3M2ZyWUef32b

Install Libraries
"""

!pip install nltk wordcloud pyLDAvis

"""| Code           | Description                               |
| -------------- | ----------------------------------------- |
| `!pip install` | Installs Python packages in Google Colab. |
| `nltk`         | Used for Natural Language Processing.     |
| `wordcloud`    | Creates Word Cloud visualizations.        |
| `pyLDAvis`     | Interactive visualization for LDA topics. |

Import Libraries
"""

import pandas as pd
import numpy as np

import nltk
import re

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation

import matplotlib.pyplot as plt
from wordcloud import WordCloud

nltk.download('stopwords')
nltk.download('wordnet')

"""| Library           | Purpose                              |
| ----------------- | ------------------------------------ |
| pandas            | Read and manipulate datasets         |
| numpy             | Numerical operations                 |
| re                | Regular expression for text cleaning |
| nltk              | Natural Language Toolkit             |
| stopwords         | Remove common English words          |
| WordNetLemmatizer | Convert words to base form           |
| CountVectorizer   | Convert text into numerical features |
| matplotlib        | Visualization                        |
| WordCloud         | Display important words              |

Download NLTK Resources
"""

nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

"""| Code      | Purpose                                |
| --------- | -------------------------------------- |
| stopwords | Downloads English stop words           |
| wordnet   | Downloads dictionary for lemmatization |
| omw-1.4   | Required for WordNet                   |

Load Dataset
"""

df = pd.read_csv("Coursera_reviews.csv")

"""| Code            | Description    |
| --------------- | -------------- |
| `pd.read_csv()` | Reads CSV file |
| `df`            | Stores dataset |

Display First Five Rows
"""

df.head()

"""Dataset Information"""

df.info()

"""Number of rows
Number of columns
Column names
Data types
Missing values

Dataset Shape
"""

df.shape

"""Column Names"""

df.columns

"""Check Missing Values"""

df.isnull().sum()

"""Select Only Review Column"""

df = df[['reviews']]

"""Rename Column

Renames the column to make it easier to reference.
"""

df.columns = ['Review']

"""Display Dataset"""

df.head()

"""Check Duplicate Reviews

Counts duplicate reviews.
"""

df.duplicated().sum()

"""Remove Duplicate Reviews"""

df.drop_duplicates(inplace=True)

"""Remove Missing Reviews

Deletes rows containing empty reviews
"""

df.dropna(inplace=True)

"""Dataset Shape Again

Displays the remaining rows after cleaning.
"""

df.shape

"""Sample Dataset

use a sample to reduce processing time.
"""

df = df.sample(10000, random_state=42)

"""| Parameter       | Description                                   |
| --------------- | --------------------------------------------- |
| sample(10000)   | Randomly selects 10,000 reviews               |
| random_state=42 | Ensures the same sample is selected every run |

Reset Index

Resets row numbers after sampling.
"""

df.reset_index(drop=True, inplace=True)

"""Display Dataset"""

df.head()

"""Create Stop Words"""

stop_words = set(stopwords.words('english'))

"""Loads English stop words such as

the
is
are
of
in
on
at

Create Lemmatizer
"""

lemmatizer = WordNetLemmatizer()

"""| Original | Lemmatized |
| -------- | ---------- |
| studies  | study      |
| running  | running    |
| cars     | car        |
| teachers | teacher    |

Text Cleaning Function
"""

def clean_text(text):

    text = str(text).lower()

    text = re.sub(r'[^a-zA-Z ]', '', text)

    words = text.split()

    words = [word for word in words if word not in stop_words]

    words = [lemmatizer.lemmatize(word) for word in words]

    return " ".join(words)

"""| Step                         | Purpose                                         |
| ---------------------------- | ----------------------------------------------- |
| Convert to string            | Handles non-text values safely                  |
| Lowercase                    | Makes matching consistent                       |
| Remove numbers & punctuation | Keeps only letters                              |
| Split into words             | Tokenization                                    |
| Remove stop words            | Removes common words                            |
| Lemmatize                    | Converts words to base form                     |
| Join                         | Converts the cleaned words back into a sentence |

Apply Cleaning

Creates a new column containing cleaned reviews.
"""

df["Clean_Review"] = df["Review"].apply(clean_text)

"""Display Results"""

df.head()

"""Check Cleaned Dataset Shape"""

df.shape

"""Online Course Reviews Dataset
                           (Coursera_reviews.csv)
                                      │
                                      ▼
                            Load Dataset (Pandas)
                                      │
                                      ▼
                          Explore the Dataset (EDA)
                  (head(), info(), shape(), columns)
                                      │
                                      ▼
                     Check Missing & Duplicate Values
                                      │
                                      ▼
                     Remove Missing & Duplicate Reviews
                                      │
                                      ▼
                      Select Only the Review Column
                                      │
                                      ▼
                        Rename Column to "Review"
                                      │
                                      ▼
                   Sample 10,000 Reviews (for faster training)
                                      │
                                      ▼
                            Reset Dataset Index
                                      │
                                      ▼
                      Download NLTK Resources
          (Stopwords, WordNet, Open Multilingual WordNet)
                                      │
                                      ▼
                        Create Stop Words Collection
                                      │
                                      ▼
                          Create WordNet Lemmatizer
                                      │
                                      ▼
                           Text Preprocessing
        ┌─────────────────────────────────────────────────────┐
        │ • Convert to Lowercase                              │
        │ • Remove Numbers                                    │
        │ • Remove Punctuation                                │
        │ • Tokenize Text                                     │
        │ • Remove Stop Words                                 │
        │ • Lemmatize Words                                   │
        └─────────────────────────────────────────────────────┘
                                      │
                                      ▼
                      Create "Clean_Review" Column
                                      │
                                      ▼
                     Cleaned Dataset Ready for LDA

| Input              | Process                           | Output                           |
| ------------------ | --------------------------------- | -------------------------------- |
| Raw Course Reviews | Data Cleaning + NLP Preprocessing | Cleaned Reviews (`Clean_Review`) |

**CountVectorizer, LDA Model, Extraction**

Import LDA

mports the LDA Topic Modeling algorithm.
"""

from sklearn.decomposition import LatentDirichletAllocation

"""| Code                        | Description                                      |
| --------------------------- | ------------------------------------------------ |
| `from`                      | Imports a specific class from a library.         |
| `sklearn.decomposition`     | Contains decomposition algorithms including LDA. |
| `LatentDirichletAllocation` | LDA algorithm used for Topic Modeling.           |

Create CountVectorizer


Creates the Count Vectorizer used as input for the LDA model.
"""

cv = CountVectorizer(
    max_df=0.95,
    min_df=2,
    stop_words='english'
)

"""| Parameter              | Description                                                 |
| ---------------------- | ----------------------------------------------------------- |
| `CountVectorizer()`    | Converts text into a numerical matrix based on word counts. |
| `max_df=0.95`          | Removes words appearing in more than 95% of documents.      |
| `min_df=2`             | Keeps words appearing in at least 2 documents.              |
| `stop_words='english'` | Removes common English stop words.                          |

Create Document-Term Matrix

Converts the cleaned reviews into numerical features for LDA.
"""

dtm = cv.fit_transform(df["Clean_Review"])

"""| Code                 | Description                                                          |
| -------------------- | -------------------------------------------------------------------- |
| `fit_transform()`    | Learns the vocabulary and converts text into a document-term matrix. |
| `df["Clean_Review"]` | Uses the cleaned review text.                                        |
| `dtm`                | Stores the document-term matrix.                                     |

Display Matrix Shape
"""

dtm.shape

"""10,000 Reviews
4,425 Unique Words

**Create LDA Model**

Creates the LDA Topic Modeling model.
"""

lda_model = LatentDirichletAllocation(
    n_components=5,
    random_state=42
)

"""| Parameter         | Description                          |
| ----------------- | ------------------------------------ |
| `n_components=5`  | Creates five hidden topics.          |
| `random_state=42` | Produces the same results every run. |

=====

Train the LDA Model
"""

lda_model.fit(dtm)

"""| Code    | Description                             |
| ------- | --------------------------------------- |
| `fit()` | Trains the LDA model.                   |
| `dtm`   | Document-Term Matrix used for training. |

=====

Learns hidden topics from the review dataset.

Display Top Words for Each Topic
"""

for index, topic in enumerate(lda_model.components_):

    print(f"\nTopic {index + 1}")

    print([cv.get_feature_names_out()[i]
           for i in topic.argsort()[-10:]])

"""| Code                      | Description                                   |
| ------------------------- | --------------------------------------------- |
| `enumerate()`             | Iterates through each topic.                  |
| `lda_model.components_`   | Stores word importance for each topic.        |
| `argsort()`               | Sorts words by weight.                        |
| `[-10:]`                  | Selects the top 10 words.                     |
| `get_feature_names_out()` | Converts word indices back into actual words. |

Calculate Topic Probabilities
"""

topic_results = lda_model.transform(dtm)

"""| Code            | Description                                                    |
| --------------- | -------------------------------------------------------------- |
| `transform()`   | Calculates topic probabilities for each review.                |
| `topic_results` | Stores the probability of each review belonging to each topic. |

Display Shape
"""

topic_results.shape

"""Display Topic Probabilities"""

topic_results

"""Assign Topic to Each Review"""

df["Topic"] = topic_results.argmax(axis=1)

"""| Code             | Description                                                     |
| ---------------- | --------------------------------------------------------------- |
| `argmax(axis=1)` | Selects the topic with the highest probability for each review. |
| `df["Topic"]`    | Stores the predicted topic number.                              |

Display Dataset
"""

df.head()

"""Count Reviews in Each Topic"""

df["Topic"].value_counts()

"""Topic Distribution Bar Chart"""

df["Topic"].value_counts().sort_index().plot(
    kind="bar",
    figsize=(8,5)
)

plt.title("Topic Distribution")

plt.xlabel("Topic Number")

plt.ylabel("Number of Reviews")

plt.show()

"""| Function           | Description                       |
| ------------------ | --------------------------------- |
| `value_counts()`   | Counts reviews per topic.         |
| `sort_index()`     | Displays topics in numeric order. |
| `plot(kind="bar")` | Creates a bar chart.              |
| `plt.show()`       | Displays the chart.               |

Clean Reviews
      │
      ▼
CountVectorizer
      │
      ▼
Document-Term Matrix
      │
      ▼
LDA Model
      │
      ▼
Train Model
      │
      ▼
Top 10 Words for Each Topic
      │
      ▼
Topic Probability
      │
      ▼
Assign Topic Number
      │
      ▼
Topic Distribution

| Review                    | Clean_Review          | Topic |
| ------------------------- | --------------------- | ----- |
| Excellent instructor      | excellent instructor  | 0     |
| Assignments are difficult | assignment difficult  | 1     |
| Worth the money           | worth money           | 2     |
| Mobile app is slow        | mobile app slow       | 3     |
| Good customer support     | good customer support | 4     |

**Visualization, Topic Prediction & Save Results**

Import pyLDAvis
"""

import pyLDAvis
import pyLDAvis.lda_model

"""| Code                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| `pyLDAvis`           | Interactive visualization library for LDA         |
| `pyLDAvis.lda_model` | Connects the trained LDA model with visualization |

Interactive Topic Visualization
"""

pyLDAvis.enable_notebook()

panel = pyLDAvis.lda_model.prepare(
    lda_model,
    dtm,
    cv
)

panel

"""| Code                | Description                                   |
| ------------------- | --------------------------------------------- |
| `enable_notebook()` | Enables visualization in Google Colab/Jupyter |
| `prepare()`         | Creates interactive visualization             |
| `panel`             | Displays topic visualization                  |

"""

import warnings

warnings.filterwarnings("ignore")

"""WordCloud for Each Topic"""

for topic_num, topic in enumerate(lda_model.components_):

    words = {
        cv.get_feature_names_out()[i]: topic[i]
        for i in topic.argsort()[-30:]
    }

    wordcloud = WordCloud(
        width=800,
        height=400,
        background_color="white"
    ).generate_from_frequencies(words)

    plt.figure(figsize=(10,5))

    plt.imshow(wordcloud)

    plt.axis("off")

    plt.title(f"Topic {topic_num}")

    plt.show()

"""| Function                      | Use                   |
| ----------------------------- | --------------------- |
| `WordCloud()`                 | Creates WordCloud     |
| `generate_from_frequencies()` | Uses LDA word weights |
| `imshow()`                    | Displays WordCloud    |
| `axis("off")`                 | Removes axis          |

Display Reviews with Topic
"""

df[["Review","Topic"]].head(20)

"""Number of Reviews per Topic"""

topic_counts = df["Topic"].value_counts().sort_index()

print(topic_counts)

"""Pie Chart"""

topic_counts.plot(
    kind="pie",
    autopct="%1.1f%%",
    figsize=(7,7)
)

plt.ylabel("")

plt.title("Topic Distribution")

plt.show()

"""Save Result

Saves the dataset with predicted topics.
"""

df.to_csv(
    "Course_Review_Topics.csv",
    index=False
)

"""Download Result"""

from google.colab import files

files.download("Course_Review_Topics.csv")

"""Predict Topic for New Review"""

new_review = [
    "The instructor explained every concept clearly and the assignments were useful."
]

"""Clean New Review"""

clean_review = clean_text(new_review[0])

"""Convert into Count Vector"""

new_dtm = cv.transform([clean_review])

"""Predict Topic"""

prediction = lda_model.transform(new_dtm)

"""Show Topic Probability"""

prediction

"""Final Predicted Topic"""

prediction.argmax()

"""Display Topic Name"""

topic_names = {
    0: "Course Content",
    1: "Instructor Quality",
    2: "Assignments",
    3: "Pricing",
    4: "Platform Experience"
}

print("Predicted Topic :", topic_names[prediction.argmax()])

"""Test Multiple Reviews"""

test_reviews = [

    "The instructor explained concepts very clearly.",

    "Assignments are difficult but useful.",

    "Course subscription is expensive.",

    "The mobile app is very slow.",

    "Excellent course content with practical examples."

]

"""Predict Topics"""

for review in test_reviews:

    cleaned = clean_text(review)

    vector = cv.transform([cleaned])

    topic = lda_model.transform(vector).argmax()

    print("Review :", review)

    print("Predicted Topic :", topic_names[topic])

    print("-"*50)

"""Coursera Reviews
        │
        ▼
Load Dataset
        │
        ▼
EDA
        │
        ▼
Text Cleaning
        │
        ▼
CountVectorizer
        │
        ▼
Document-Term Matrix
        │
        ▼
LDA Model (5 Topics)
        │
        ▼
Train Model
        │
        ▼
Top Words
        │
        ▼
Assign Topic
        │
        ▼
Topic Distribution
        │
        ▼
WordCloud
        │
        ▼
pyLDAvis
        │
        ▼
Predict New Reviews
        │
        ▼
Save CSV
"""