# -*- coding: utf-8 -*-
"""Customer Support Ticket Classification Using Hashing Vectorizer and Multinomial Naive Bayes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yu-i9JQG7RI6SFDjEl3LM0oPZmAe942u

Import Libraries
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)

"""Upload Dataset"""

df = pd.read_csv("customer_support_tickets.csv")

"""Display First 5 Rows"""

df.head()

"""Dataset Shape"""

df.shape

"""Dataset Information"""

df.info()

"""Statistical Summary"""

df.describe(include="all")

"""count → Total non-missing records.
unique → Number of different values.
top → Most common value.
freq → Number of times the most common value appears.

Check Missing Values
"""

df.isnull().sum()

"""Display Column Names"""

df.columns

"""Keep Required Columns"""

df = df[['Ticket_Description', 'Issue_Category']]

"""Display Dataset"""

df.head()

"""Check Class Distribution"""

df["Issue_Category"].value_counts()

"""Plot Category Distribution"""

df["Issue_Category"].value_counts().plot(
    kind="bar",
    figsize=(10,5),
    color="skyblue"
)

plt.title("Issue Category Distribution")
plt.xlabel("Category")
plt.ylabel("Count")
plt.xticks(rotation=45)

plt.show()

"""Define Features and Target"""

X = df["Ticket_Description"]

y = df["Issue_Category"]

"""Check Missing Values"""

df[['Ticket_Description', 'Issue_Category']].isnull().sum()

"""Remove Missing Rows ("""

df = df.dropna(subset=['Ticket_Description', 'Issue_Category'])

df[['Ticket_Description', 'Issue_Category']].isnull().sum()

X = df["Ticket_Description"]

y = df["Issue_Category"]

"""Split Dataset"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

"""Apply Hashing Vectorizer"""

vectorizer = HashingVectorizer(
    n_features=2**12,
    alternate_sign=False
)

X_train_hash = vectorizer.transform(X_train)

X_test_hash = vectorizer.transform(X_test)

"""Train Model"""

model = MultinomialNB()

model.fit(X_train_hash, y_train)

"""Predict Test Data"""

y_pred = model.predict(X_test_hash)

"""Accuracy"""

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy :", accuracy)

"""Accuracy Interpretation
-----------------------


| Metric     | Value      |
| ---------- | ---------- |
| Accuracy   | **0.9996** |
| Percentage | **99.96%** |
| Error Rate | **0.04%**  |

Classification Report
"""

print(classification_report(y_test, y_pred))

"""Confusion Matrix"""

cm = confusion_matrix(y_test, y_pred)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=model.classes_
)

disp.plot(cmap="Blues")

plt.show()

"""| Category        | Total Test Tickets | Correct Predictions | Wrong Predictions |
| --------------- | -----------------: | ------------------: | ----------------: |
| Account         |                556 |                 556 |                 0 |
| Billing         |                705 |                 705 |                 0 |
| Fraud           |                150 |                 149 |                 1 |
| General Inquiry |                541 |                 541 |                 0 |
| Technical       |                816 |                 816 |                 0 |

Predict New Ticket
"""

ticket = [
    "I forgot my password and cannot login."
]

ticket_hash = vectorizer.transform(ticket)

prediction = model.predict(ticket_hash)

print("Predicted Category :", prediction[0])

"""Try More Examples"""

ticket = [
    "Payment deducted twice from my bank account"
]

ticket_hash = vectorizer.transform(ticket)

print(model.predict(ticket_hash))

ticket = [
    "The application crashes whenever I open it"
]

ticket_hash = vectorizer.transform(ticket)

print(model.predict(ticket_hash))

ticket = [
    "Refund has not been credited to my account"
]

ticket_hash = vectorizer.transform(ticket)

print(model.predict(ticket_hash))

"""Save Model"""

import joblib

joblib.dump(model, "customer_support_model.pkl")

"""| Input                          | Process                                 | Output                            |
| ------------------------------ | --------------------------------------- | --------------------------------- |
| Trained Machine Learning Model | `joblib.dump()` saves the model to disk | `customer_support_model.pkl` file |

===========


Work flow
---------

| Step | Action                                     | Result                                        |
| ---- | ------------------------------------------ | --------------------------------------------- |
| 1    | Train the model                            | Model learns patterns from the training data  |
| 2    | Save the model using `joblib.dump()`       | Model is stored as a `.pkl` file              |
| 3    | Load the model later using `joblib.load()` | Model can make predictions without retraining |

===========
| Benefit            | Explanation                                                                      |
| ------------------ | -------------------------------------------------------------------------------- |
| Saves time         | No need to train the model every time the program runs.                          |
| Faster prediction  | Directly loads the trained model for inference.                                  |
| Easy deployment    | The saved model can be used in Streamlit, Flask, Django, or Hugging Face Spaces. |
| Reusable           | The same trained model can be shared or reused in other applications.            |
| Preserves training | Keeps all the learned parameters from the training process.                      |

Save Hashing Vectorizer
"""

joblib.dump(vectorizer, "hashing_vectorizer.pkl")

"""Load Saved Model"""

model = joblib.load("customer_support_model.pkl")

vectorizer = joblib.load("hashing_vectorizer.pkl")

"""| Benefit                       | Explanation                                                             |
| ----------------------------- | ----------------------------------------------------------------------- |
| Consistent feature extraction | Ensures new text is converted into features exactly as during training. |
| Faster deployment             | No need to recreate the vectorizer each time the application starts.    |
| Required for prediction       | The saved model expects input transformed by the same vectorizer.       |
| Easy deployment               | Used in Streamlit, Flask, Django, or Hugging Face applications.         |
| Reusable                      | Can be shared and reused across different systems.                      |

==========

| Step | File Used                    | Action                                                                         |
| ---- | ---------------------------- | ------------------------------------------------------------------------------ |
| 1    | `hashing_vectorizer.pkl`     | Convert customer ticket text into numerical features                           |
| 2    | `customer_support_model.pkl` | Predict the issue category from those features                                 |
| 3    | Output                       | Display the predicted category (e.g., **Billing**, **Technical**, **Account**) |

"""